import ModulePage from '../components/ModulePage.jsx'
import { getReports } from '../services/reportService.js'

function ReportsPage() {
  return (
    <ModulePage
      title="Reports"
      description="Analytics exports"
      fetcher={getReports}
      columns={['Report', 'Type', 'Generated By', 'Date']}
      emptyMessage="No report records are available from the backend yet."
      renderItem={(item) => (
        <>
          <td>{item.report_name || item.name || item.id || '—'}</td>
          <td>{item.report_type || item.type || '—'}</td>
          <td>{item.generated_by || item.owner || '—'}</td>
          <td>{item.created_at || item.date || '—'}</td>
        </>
      )}
    />
  )
}

export default ReportsPage
